<x-layouts::app :title="$title">
    <div class="mx-auto max-w-3xl space-y-6 p-6 lg:p-10"><a class="text-sm font-semibold text-amber-600" href="{{ url()->previous() }}">Volver</a><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-amber-600">{{ $team->name }}</p><h1 class="mt-2 text-3xl font-bold">{{ $title }}</h1></div>
        <form method="POST" action="{{ isset($item) ? route($resource.'.update', [$team->slug, $item]) : route($resource.'.store', $team->slug) }}" class="space-y-5 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-900">@csrf @isset($item) @method('PUT') @endisset
            @if (in_array($resource, ['publicaciones', 'noticias', 'juegos', 'hilos', 'problemas']))<label class="block text-sm font-semibold">Titulo<input name="titulo" value="{{ old('titulo', $item->titulo ?? '') }}" required maxlength="180" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if (in_array($resource, ['comunidad', 'foros', 'canales', 'plataformas', 'idiomas', 'etiquetas']))<label class="block text-sm font-semibold">Nombre<input name="nombre" value="{{ old('nombre', $item->nombre ?? '') }}" required maxlength="100" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'reportes-soporte')<label class="block text-sm font-semibold">Asunto<input name="asunto" value="{{ old('asunto', $item->asunto ?? '') }}" required maxlength="150" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'idiomas')<label class="block text-sm font-semibold">Codigo<input name="codigo" value="{{ old('codigo', $item->codigo ?? '') }}" required maxlength="5" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if (in_array($resource, ['foros', 'hilos', 'aportes', 'canales']))<label class="block text-sm font-semibold">ID relacionado<input name="{{ $resource === 'foros' || $resource === 'canales' ? 'comunidad_id' : ($resource === 'hilos' ? 'id_foro' : 'id_hilo') }}" type="number" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'canales')<label class="block text-sm font-semibold">Tipo<select name="tipo" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"><option value="texto">Texto</option><option value="voz">Voz</option></select></label>@endif
            @if ($resource === 'juegos')<label class="block text-sm font-semibold">Desarrollador<input name="desarrollador" value="{{ old('desarrollador', $item->desarrollador ?? '') }}" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label><label class="block text-sm font-semibold">Fecha de lanzamiento<input name="fecha_lanzamiento" type="date" value="{{ old('fecha_lanzamiento', isset($item->fecha_lanzamiento) ? $item->fecha_lanzamiento->format('Y-m-d') : '') }}" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'comentarios')<label class="block text-sm font-semibold">ID de publicacion<input name="id_publicacion" type="number" value="{{ old('id_publicacion', $item->id_publicacion ?? '') }}" required class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if (! in_array($resource, ['canales', 'plataformas', 'idiomas', 'etiquetas']))<label class="block text-sm font-semibold">Descripcion o contenido<textarea name="{{ in_array($resource, ['comunidad', 'foros', 'problemas', 'reportes-soporte']) ? 'descripcion' : 'contenido' }}" rows="8" required class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800">{{ old('contenido', $item->contenido ?? old('descripcion', $item->descripcion ?? '')) }}</textarea></label>@endif
            @if ($errors->any())<div role="alert" class="space-y-1 text-sm text-red-600"><p>Corrige los siguientes errores:</p><ul class="list-disc ps-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <button type="submit" class="rounded-lg bg-amber-500 px-5 py-2 font-semibold text-zinc-950 hover:bg-amber-400">Guardar</button>
        </form>
    </div>
</x-layouts::app>
